server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/springdemo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: devuser
        password: devuser
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            initialSize: 5
            minIdle: 5
            maxActive: 100
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false # 申请连接时直接检测连接是否有效.申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            testOnReturn: false # 归还连接时检测连接是否有效.归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            poolPreparedStatements: true # 开启PSCache
            maxPoolPreparedStatementPerConnectionSize: 20 #设置PSCache值
            connectionErrorRetryAttempts: 3 # 连接出错后再尝试连接三次
            breakAfterAcquireFailure: true # 数据库服务宕机自动重连机制
            timeBetweenConnectErrorMillis: 300000 # 连接出错后重试时间间隔
            asyncInit: true
            remove-abandoned: true # 是否自动回收超时连接
            remove-abandoned-timeout: 1800 # 超时时间(以秒数为单位)
            transaction-query-timeout: 6000 # 事务超时时间
            filters: stat,wall,log4j2
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    thymeleaf:
        mode: HTML
        encoding: utf-8
        cache: true
        prefix: classpath:templates/
    messages:
        basename: static/i18n/messages

